%%

classDiagram
direction LR

    class Operator{
    }

    class Ichor{
    }

    class Motor_Driver{
    }

    class Current_Monitor{
    }

    class Rotary_Encoder{
    }

    class Homing_Switch{
    }

    class Motor{
    }


    Operator --> Ichor: Gives exact movement commands
    Operator <-- Ichor: Gives telemetry
    Ichor --> Motor_Driver: commands (I2C)
    Motor_Driver --> Motor: drives

    Motor --> Homing_Switch: presses
    Motor --> Rotary_Encoder: spins

    Ichor <-- Homing_Switch: triggers
    Ichor <-- Rotary_Encoder: triggers


    Motor <-- Current_Monitor: monitors (analog)
    Ichor --> Current_Monitor: monitors (SPI)
